site_name: nmTeam Support Documentation
theme:
  name: material
  logo: https://websiteres.nmteam.xyz/producticon/nmTeam/logo@128.png
  favicon: https://websiteres.nmteam.xyz/producticon/nmTeam/logo@128.png
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: лɫģʽ
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: лǳɫģʽ
extra_css: [docsList.css]
docs_dir: generated

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nm-Team/nmBot-Telegram-doc
copyright: Copyright 2022-2024 nmTeam. All rights reserved. <br>nmTeam Support Documentation is licensed under the MIT License.

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
# Contents below are automatically generated by the script.
# NAV_ARIA_START
  - nmTeam 支持文档: '/'
  - nmBot Telegram 帮助文档:
    - nmBot Telegram 帮助文档: 'nmbot-telegram/'
    - nmBot 积分:
        - nmBot 积分: 'nmbot-telegram/credit/credit.md'
    - 问答:
        - 关于看起来由 nmBot 发送的消息: 'nmbot-telegram/faq/about-message-content-of-bot.md'
        - 如果您无法访问 nmBot 面板: 'nmbot-telegram/faq/cannot-access-panel.md'
        - 如果您无法在 nmBot 面板登录: 'nmbot-telegram/faq/cannot-log-in-to-panel.md'
        - 如果“频道验证”在您的群组中不工作: 'nmbot-telegram/faq/channel-verification-not-working.md'
        - nmBot /pm 指令提示“可能是 Telegram 会员”: 'nmbot-telegram/faq/pm_might_be_premium.md'
    - 群组功能:
        - 操作记录: 'nmbot-telegram/group/action-log.md'
        - nmBot 群组功能所需权限说明: 'nmbot-telegram/group/admin-rights-and-features.md'
        - 自动识别并删除骚扰消息: 'nmbot-telegram/group/anti-spam.md'
        - 使用 ban、block 指令禁言或封禁成员和频道: 'nmbot-telegram/group/ban.md'
        - banme: 'nmbot-telegram/group/banme.md'
        - 频道透视眼: 'nmbot-telegram/group/channel-perspective-eye.md'
        - 群组娱乐功能: 'nmbot-telegram/group/games.md'
        - 授予 nmBot 管理员权限并配置功能: 'nmbot-telegram/group/group-setup.md'
        - nmBot Telegram 会员身份鉴定指令: 'nmbot-telegram/group/is-premium.md'
        - 入群验证: 'nmbot-telegram/group/join-verification.md'
        - 关键词回复: 'nmbot-telegram/group/key-word-reply.md'
        - 群友互动: 'nmbot-telegram/group/members-interaction.md'
        - 使用 pin 指令置顶或取消置顶消息: 'nmbot-telegram/group/pin.md'
        - 在 nmBot 面板管理群组（若面板中找不到群组）: 'nmbot-telegram/group/reg-panel.md'
        - 同频气氛组  : 'nmbot-telegram/group/reply-channel.md'
        - 允许 nmTeam 支持解封误封用户: 'nmbot-telegram/group/unban-users-banned-by-anti-spam.md'
        - 使用 warn 指令警告成员和频道: 'nmbot-telegram/group/warn.md'
    - 法律信息:
        - nmBot 服务隐私政策: 'nmbot-telegram/legal/privacy-policy.md'
        - nmBot 服务使用条款: 'nmbot-telegram/legal/terms-of-use.md'
    - nmBot 更新日志:
        - nmBot 更新日志: 'nmbot-telegram/update-log/'
        - nmBot NEXT (2024 年 6 月) 更新日志: 'nmbot-telegram/update-log/nmbot-next.md'
        - nmBot 2024 年 7 月功能更新: 'nmbot-telegram/update-log/2024-07.md'
        - nmBot 2024 年 2 月功能更新: 'nmbot-telegram/update-log/2024-02.md'
        - nmBot 2024 年 1 月功能更新: 'nmbot-telegram/update-log/2024-01.md'
        - nmBot 2023 年 12 月功能更新: 'nmbot-telegram/update-log/2023-12.md'
        - nmBot 2023 年 11 月功能更新: 'nmbot-telegram/update-log/2023-11.md'
        - nmBot 2023 年 10 月功能更新: 'nmbot-telegram/update-log/2023-10.md'
        - nmBot 2023 年 9 月功能更新: 'nmbot-telegram/update-log/2023-09.md'
        - nmBot 2023 年 8 月功能更新: 'nmbot-telegram/update-log/2023-08.md'
        - nmBot 2023 年 7 月功能更新: 'nmbot-telegram/update-log/2023-07.md'
        - nmBot 2023 年 6 月功能更新: 'nmbot-telegram/update-log/2023-06.md'
        - nmBot 2023 年 5 月功能更新: 'nmbot-telegram/update-log/2023-05.md'
        - nmBot 2023 年 4 月功能更新: 'nmbot-telegram/update-log/2023-04.md'
        - nmBot 2023 年 3 月功能更新: 'nmbot-telegram/update-log/2023-03.md'
        - nmBot 2023 年 2 月功能更新: 'nmbot-telegram/update-log/2023-02.md'
        - nmBot 2023 年 1 月功能更新: 'nmbot-telegram/update-log/2023-01.md'
        - 归档的 nmBot 更新日志: 'nmbot-telegram/update-log/previous-log.md'
    - 关于 nmBot 面板: 'nmbot-telegram/about-panel.md'
    - 关于 nmBot: 'nmbot-telegram/about.md'
    - 关于 nmBot 预览版: 'nmbot-telegram/beta.md'
    - 启动 nmBot 面板: 'nmbot-telegram/launch-panel.md'
    - nmartChat 智能聊天: 'nmbot-telegram/nmartchat.md'
    - 设置 nmBot 语言: 'nmbot-telegram/set-language.md'
    - nmBot 支持: 'nmbot-telegram/support.md'
  - 关于 nmTeam 帮助文档: 'about.md'
# NAV_ARIA_END